### ISSUE TITLE
[Bug Fix] Assign Message IDs

### ISSUE THREAD

**Issue by ASimpleNasaEngineer** [nasa/CCDD#72] opened 2020-02-12 00:50 UTC
Assigning Message IDs, no matter the structure, does not assign new starting MsgIDs. No Error message is given and is assumed to work, but feature does not work.

**Comment by jmacneal** [comment] 2020-02-17 23:02
This functionality appears to be broken. I've created an issue on our internal repo. I'll provide updates on the issue's status here.

**Comment by jmacneal** [comment] 2020-02-25 23:40
@ASimpleNasaEngineer  If possible, could you provide any additional information about the database you were using? I'm having a hard time reproducing the behavior.

**Comment by ASimpleNasaEngineer** [comment] 2020-03-12 19:41
The database we are using is pulling C from cFS and converting it into csv that is imported into CCDD. Once the MsgIDs, TLM, Struct, etc. are impoted, our MsgIDs are already have assigned numbers. The issue comes when I try to mass re-assign MsgIDs and nothing happens.

**Comment by KevinMcCluney** [comment] 2020-03-16 16:20
Just to make sure, did you check the "Overwrite existing IDs" boxes in each of the tabs in the "Assign Message IDs" dialog?

**Comment by ASimpleNasaEngineer** [comment] 2020-03-17 21:46
We did. We also gave a range of MsgIDs to assign to.

**Comment by bawi235** [comment] 2020-05-05 17:11
I attempted to recreate this issue, but I am having no luck. What version of CCDD are you using? If it is version 2 have you tried the newest release, version 2.0.20?

**Comment by nasa7120** [comment] 2020-07-07 19:15
Attempted to recreate this issue but had no success. 
Issue is being closed due to inability to replicate.
If this problem persists, feel free to open a new issue with replication steps and details on postgres versions etc..

Details:
- Used CCDD Version 2.0.21 (the latest at the time of writing) and performed the following
- Used an existing database and assigned both Structure and Command MIDs
  - Both the structure and Command MIDs updated correctly, started at the expected address and skipped any reserved ID blocks
- Created a new database and new command structure with an assigned MID through the table editor
  - Using Data > Message IDs > Assign Message IDs dialog, checked the "Overwrite existing IDs" and updated the MID
    - This worked as expected
  - Created a second table and assigned it an MID through the table editor
  - Using Data > Message IDs > Assign Message IDs dialog, checked the "Overwrite existing IDs" and updated the MIDs
    - Both MIDs were updated as expected
  - Added in a reserved Message ID located at 0xa4
  - Using Data > Message IDs > Assign Message IDs dialog, checked the "Overwrite existing IDs", a starting address of 0xa3 and updated
    - The resultant generated MID's were 0xa3 and 0xa5
    - This respects the reserve block and updates the MIDs

**Comment by nasa7120** [comment] 2020-07-07 19:17
Closed due to inability to replicate.

**Closed** 2020-07-07 19:17 UTC
