### ISSUE TITLE
CCDD returns 0 (Success) with database errors

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#50] opened 2018-11-19 17:59 UTC
When I attempt to connect to a project which is already open, I (correctly) get the following error message:
```
Database Error : Cannot delete project database 'localhost:1234/myproject'; cause 'ERROR: database "myproject" is being accessed by other users
  Detail: There is 1 other session using the database.'
```
however CCDD still exits with exit code 0 (Success). It would be helpful if it returned a non-zero exit code so that calling program can handle the error. This is a similar issue to #47 where it was noted that CCDD (used to) return 0 on a password authentication failure.

**Comment by KevinMcCluney** [comment] 2018-11-26 18:12
Version 1.4.49 addresses this issue.  This turned up some other potential issues, resulting in more extensive changes than expected.  These changes affect command line command handling in particular.  If an error occurs (one that generates an exit code of 1) then command line processing stops immediately; if the GUI is hidden then the application exits.

Note that the 'delete' command's 'noMessage' sub-command is replaced with a new sub-command, 'continueIfMissing'.  The effect is essentially the same when the GUI is hidden (i.e., -shutdown is used) - if the continueIfMissing is used and the specified project doesn't exist then command line processing continues (no messages).  If the argument isn't used and the project doesn't exist then an error message is displayed and the application exits.

**Comment by ascended121** [comment] 2018-11-27 13:46
It would be helpful if you could include the new CCDD version in commit messages to make it easier to identify the commit with a particular version of CCDD (rather than pulling commits until you find the desired version).

In particular, I'm a little confused about your last commit (9060b7e). The commit message seems to include the change you mentioned above, however the version number in that commit is still at 1.4.48 and the help output by the CCDD CLI still indicates a NoMessage sub-command. This is confirmed by attempting to use the new continueIfMissing sub-command which results in:
```
Error: Unrecognized command 'continueIfMissing'
```

**Comment by KevinMcCluney** [comment] 2018-11-27 15:17
I'll try to remember to include the version.

I just downloaded what's in the repository and it says version 1.4.49.  I verified the new command as well.

**Comment by ascended121** [comment] 2018-11-27 16:02
Whoops, ended up being a git issue on my side, but still think the version numbers in the commit message would be helpful. The new subcommand is now working. Thanks!

I'm now getting the following
Cmd: 
```
java -cp "C:\path\to\ccdd\CCDD.jar" CCDD.CcddMain -logPath "C:\path\to\logs" -import "-fileName 'C:/path/to/my/file.json' -replaceExisting true" -project 'myproj' -user myuser -shutdown
```

Exit code: 0
StdErr:
```
CCDD : Database Error : Cannot connect to project database 'localhost:5432/_myproj_' as user 'myuser'; cause 'FATAL: database "_myproj_" does not exist'
```
I can verify that project exists through the GUI. Also note the success exit code despite the error.

**Comment by KevinMcCluney** [comment] 2018-11-27 19:01
The incorrect exit code is due to a bad conditional statement - it'll be corrected in the next release.

So far I haven't been able to reproduce the "cannot connect" error.  It's significant that the command line uses **myproj** as the project name, but the error message shows the database name as **\_myproj_**.  The project name is converted to an acceptable postgreSQL name when the project database is created (the original name is stored).  Any invalid character in the project name is converted to an underscore, all capital letters are forced to lower case, and the result is the database name.  SO in this case I don't understand why it's performing a conversion on the project name.  Try removing the single quotes from around the project name and see if you get the same result.

**Comment by KevinMcCluney** [comment] 2018-11-27 19:38
I did find an error in the import command line command where the project name vs the database name is passed to a method.  This correction will be in the next release.

**Comment by SpaceSteve121** [comment] 2018-11-27 20:46
Removing the quotes does seem to have resolved the issue... I did notice some inconsistency in the ability to use quotes... you can enclose the project name in quotes for the name sub-command of the create and delete commands, but the errors above occur when the project command is used with a quoted name. 

For my current project name I don't need the quotes, so I'll work around by removing them for now.

**Comment by ascended121** [comment] 2018-11-27 20:47
Removing the quotes does seem to have resolved the issue... I did notice some inconsistency in the ability to use quotes... you can enclose the project name in quotes for the name sub-command of the create and delete commands, but the errors above occur when the project command is used with a quoted name.

For my current project name I don't need the quotes, so I'll work around by removing them for now.

**Comment by KevinMcCluney** [comment] 2018-11-27 20:57
Did you try using double versus single quotes?

**Comment by KevinMcCluney** [comment] 2018-11-28 14:37
I reproduced the problem in Windows.  Windows doesn't recognize single quotes as bounding characters around command line arguments (however, single quotes bounded by double quotes, as is used in sub-commands, are handled by CCDD, so are parsed as expected).  Windows does accept double quotes.  I've added code to the next release (1.4.50) that strips bounding quotes (single or double) from command line arguments.  The Linux command line parser already does this, so there's no net effect when running in Linux.  The Windows command line parser already does this for double quotes, so the effect of the new code is to allow the use of single quotes while running in Windows.

**Comment by KevinMcCluney** [comment] 2018-12-11 15:06
Version 1.4.57, which should be uploaded by COB, corrects this.  I've tested numerous permutations, primarily using the -project and -delete commands with existing/non-existing projects, and with/without the -continueIfMissing flag, and the exit status was reported correctly in every instance.

**Comment by ascended121** [comment] 2018-12-11 15:38
Sounds good, I'll look forward to that version.

Would it be possible to include your test suite in the repo? I'd be happy to contribute tests for all of my use-cases/CLI command combinations if that would help stabilize the CLI interface.

**Comment by KevinMcCluney** [comment] 2018-12-11 19:39
There is no test suite.  It would certainly be a welcome addition and would improve the reliability of the updates, so I'd be happy to collect any contributions and post them on the repository.

**Closed** 2018-12-12 18:54 UTC
