### ISSUE TITLE
Possible Command Import Bug? 

### ISSUE THREAD

**Issue by mprel** [nasa/CCDD#10] opened 2018-05-24 18:27 UTC
I'm currently integrating a C2 system called COSMOS with CCDD for use with CubeSats. The telemetry configuration file integration has gone smoothly and is now automated. However, when importing commands into CCDD using CSV format I have noticed the Arg 1 Minimum and Arg 1 Maximum fields, when given column values, seem to stymie importation. It's almost certainly isolated to these two fields as I added a custom "Endianness" field at the end using the Table Type Editor and this was rendered fine into CCDD whenever I deleted any values for Arg 1 Minimum and Arg 1 Maximum. Any addition of these values causes the entire table to fail to load.  I was wondering if you're aware of any outstanding bug.  I cannot attach any example files I have been working with as they may contain classified information, but you can e-mail me at matthew.t.prelich@nasa.gov if you wish to speak further about this issue. Your name did not have an associated e-mail listed with it in the internal global address book.

**Comment by KevinMcCluney** [comment] 2018-05-24 20:12
I wasn't aware of a bug. I'm on vacation until 6/4, so I'll be able to address the issue when I get back to the office. I apologise for the inconvenience.

**Comment by mprel** [comment] 2018-05-24 20:33
That is perfectly fine. I found your e-mail in the global address book (it was listed twice for some reason and only the second one had your contact information). I will send you the files I am referring to as it may be hard to decipher what I mean. Thank you.

**Comment by lopezdp** [comment] 2018-05-25 01:08
@KevinMcCluney If you dont mind, I'd like to give it a shot while youre on vacation. Id like to try to see if I can come up with a solution for it. @mprel Im familiar with the data model in the CCDD so I dont need to see your data (although it would help), and if you could just give me a simple example of the data structure in terms of how many nested structures deep it is, then I can recreate a db to test against what you could possibly need. At the very least I can import something that looks like a command struct and try to recreate the error and see where it leads me... @KevinMcCluney let me know if you got any pointers and hope youre doing great!

**Comment by mprel** [comment] 2018-05-25 17:00
@KevinMcCluney Did a "David Lopez" comment here last night? I received an e-mail notification that he did saying he would like to examine a possible issue, but I do not see any such sign of this today. Is he affiliated with JPL, Goddard, or Kennedy? I ask because there are three of such names in the nasa.gov address book, and I'd like to send him an e-mail since he asked about it. I'm not sure what happened in this regard. Perhaps he deleted his comment.

**Comment by lopezdp** [comment] 2018-05-25 19:52
@mprel sorry about that, just thought Id play around with it first to try to reproduce the bug and then get back to you if i could find something before kevin. I just interned with him last summer you wont find me in the email. Im just familiar with the CCDD and can probably figure it out... maybe... Ill let you know if i find anything and can produce some results.

**Comment by mprel** [comment] 2018-05-25 20:04
@lopezdp Okay cool. Do you have an e-mail I can reach you at? You'll be able to understand the problem with just two files.

**Comment by KevinMcCluney** [comment] 2018-06-05 19:16
This issue was resolved with the user off-line.  The version of CCDD in use by the user was old, causing many of the issues. There was a bug that prevented values larger than an integer from being used in the minimum and maximum columns; this has been corrected as of version 1.2.32.

**Closed by KevinMcCluney** 2018-06-05 19:16 UTC
