### ISSUE TITLE
CCDD hangs when running script via -execute

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#12] opened 2018-06-08 13:30 UTC
The command shown below is intended to run a script on a group to generate outputs. The documentation states that the -execute argument should result in a headless run of the script, however the CCDD Gui window pops up unexpectedly. Many queries are run and then the output freezes. After several minutes I ended up terminating CCDD due to apparent inactivity.

Command:
```java -cp C:\My\Absolute\CCDD\Path\CCDD.jar CCDD.CcddMain -logPath C:\My\Absolute\Log\Path -project myProject -user myUser -password #### -execute 'myScript.js:Group:myGroup' -scriptOutPath C:\My\Absolute\Out\Path```

Running the same database/same user/same script/same group/same paths via the GUI completes successfully in several seconds. I also observe this behavior when attempting to call one of the standard scripts, itosRecFile.js.

Not sure if its relevant/equatable, but starting the Gui, running the script, and closing the Gui resulted in 249 entries in the log file whereas running the script via the -execute argument results in ~50,000 entries in the log file before it stops updating and I terminate CCDD. I haven't closely examined the logs, but that seems to indicate that its doing vastly different things in each case.

Not sure if its relevant, but when letting the script run until the log stops updating (after several minutes), I notice that the last two entries are always:
```
localhost:5432|myProject|myUser|06/08/2018 08:57:43.015|Success|Project 'myProject' unlocked
localhost:5432|myProject|myUser|06/08/2018 08:57:43.016|Success|Project database 'myProject' closed
```

This was demonstrated on:
OS: Win10
CCDD: 1.2.37 6-7-2018
Java: 1.8.0_171 (64-bit)
PostgreSQL: 10.4
JDBC: PostgreSQL 9.4.1207.jre7 (type 4)
Jetty 9.2.18.v20160721

**Comment by KevinMcCluney** [comment] 2018-06-08 15:08
The user's guide is out of date - it should be back up to speed sometime next week.  The addition of the import and export command line commands prompted a change to allow the program to continue execution, with the GUI displayed after the command completes.  The script execution was changed to perform in the same way.  A new command line command, '-shutdown', if added to the command line causes the GUI to not display and forces CCDD to close once the import/export/script execution completes.
The command line script execution had a bug (caused by the aforementioned change, which resulted n an infinite loop) - this is fixed in the latest CCDD version.

**Comment by ascended121** [comment] 2018-06-08 15:26
Thanks, can confirm using -execute option no longer hangs and -shutdown operation replicates old -execute functionality. Thanks!

**Closed** 2018-06-08 15:27 UTC
